name: Build OpenWrt for JDCloud AX1800 PRO

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: "Enable SSH debugging"
        required: false
        default: "true"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python3 unzip wget zlib1g-dev \
          rsync qemu-utils

    - name: Clone LiBwrt OpenWrt
      run: |
        git clone --depth=1 https://github.com/LiBwrt/openwrt-6.x openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Add Plugins
      run: |
        cd openwrt/package
        mkdir -p custom

    - name: Setup tmate session (SSH debug)
      if: ${{ github.event.inputs.ssh == 'true' || contains(github.event.head_commit.message, '[ssh]') }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false  # 仅允许触发者访问 SSH 会话
        
    - name: Start Compile
      run: |
        cd openwrt
        make download -j$(nproc) || make download -j1 V=s
        make -j$(nproc) || make -j1 V=s

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-JDCloud-AX1800PRO
        path: |
          openwrt/bin/targets/*/*/*.bin
